# Generated by Django 5.0.6 on 2024-11-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
    ]
