# Generated by Django 5.0.6 on 2024-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfl_app', '0002_remove_userpreference_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('daytime_temperature', models.FloatField()),
                ('nighttime_temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('uv_index', models.FloatField()),
                ('typhoon_season', models.CharField(max_length=255)),
                ('best_month', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('snowfall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('mountain_hills', models.BooleanField()),
                ('forest', models.BooleanField()),
                ('beach', models.BooleanField()),
                ('city', models.BooleanField()),
                ('village', models.BooleanField()),
                ('cave', models.BooleanField()),
                ('stream', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TouristActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('park', models.BooleanField()),
                ('historical_sites', models.BooleanField()),
                ('outdoor_adventures', models.BooleanField()),
                ('water_activities', models.BooleanField()),
                ('food_experience', models.BooleanField()),
                ('festivals', models.BooleanField()),
                ('relaxation_health', models.BooleanField()),
                ('nightlife', models.BooleanField()),
                ('wildlife_nature', models.BooleanField()),
                ('shopping', models.BooleanField()),
            ],
        ),
    ]
