# Generated by Django 5.0.6 on 2024-11-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfl_app', '0003_climatedata_geofeature_provincedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='best_month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='daytime_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='nighttime_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='snowfall',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='typhoon_season',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='uv_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='provincedescription',
            name='province',
            field=models.CharField(max_length=10000),
        ),
    ]
