# Generated by Django 5.0.6 on 2024-11-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfl_app', '0004_alter_climatedata_best_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatedata',
            name='snowfall',
        ),
    ]
