# Generated by Django 5.0.6 on 2024-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfl_app', '0005_remove_climatedata_snowfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='daytime_temperature',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='nighttime_temperature',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='precipitation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='uv_index',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
